//定义程序里要用到的那个kv常量,如策略类型等. 用js的格式, 是方便使用json来做解析. 还可以充分利用ide来做检查
//注意请按以下格式增加内容即可,不要改变格式.
var reportClassifyConfig =
    [
        {
            "code":"P3206",
            "name":"策略研究"
        },
        {
            "code":"P3201",
            "name":"晨会纪要"
        },
        {
            "code":"P3202",
            "name":"宏观研究"
        },
        {
            "code":"P3203",
            "name":"行业研究",
            children:[
                {
                    "code":"A",
                    "name":"农、林、牧、渔业"
                },
                {
                    "code":"B",
                    "name":"采矿业"
                },
                {
                    "code":"C",
                    "name":"制造业"
                },
                {
                    "code":"D",
                    "name":"电力、热力、燃气及水生产和供应业"
                },
                {
                    "code":"E",
                    "name":"建筑业"
                },
                {
                    "code":"F",
                    "name":"批发和零售业"
                },
                {
                    "code":"G",
                    "name":"交通运输、仓储和邮政业"
                },
                {
                    "code":"H",
                    "name":"住宿和餐饮业"
                },
                {
                    "code":"I",
                    "name":"信息传输、软件和信息技术服务业"
                },
                {
                    "code":"J",
                    "name":"金融业"
                },
                {
                    "code":"K",
                    "name":"房地产业"
                },
                {
                    "code":"L",
                    "name":"租赁和商务服务业"
                },
                {
                    "code":"M",
                    "name":"科学研究和技术服务业"
                },
                {
                    "code":"N",
                    "name":"水利、环境和公共设施管理业"
                },
                {
                    "code":"O",
                    "name":"居民服务、修理和其他服务业"
                },
                {
                    "code":"P",
                    "name":"教育"
                },
                {
                    "code":"Q",
                    "name":"卫生和社会工作"
                },
                {
                    "code":"R",
                    "name":"文化、体育和娱乐业"
                },
                {
                    "code":"S",
                    "name":"综合"
                }
            ]
        },
        {
            "code":"P3204",
            "name":"公司研究"
        },
        {
            "code":"P3209",
            "name":"期货研究"
        },
        {
            "code":"P3207",
            "name":"债券研究"
        },
        {
            "code":"P3208",
            "name":"基金研究"
        },
        {
            "code":"P3299",
            "name":"其他"
        }
    ]
